### ISSUE TITLE
Upgrade cereal to newest version?

### ISSUE THREAD

**Issue by runeksvendsen** [plaprade/murmur3#4]
Hello

A new minor version of cereal has been released: 0.5.3.0. 

In order for a package of mine (bitcoin-payment-channel) to be accepted into the stackage repo, murmur3 - being a haskoin-core dependency - needs an update to use the newest cereal: https://github.com/fpco/stackage/pull/1750#issuecomment-236729636

Would it be possible for you to release a new version of murmur3 on Hackage, with the cereal dependency updated to accept 0.5.3.0?

**Comment by m0dev76** [comment]
Hi, sure. I've uploaded murmur3-1.0.3 with relaxed dependencies.

**Comment by runeksvendsen** [comment]
Perfect! Thank you sir.
